class Food {
  String? imgUrl;
  String? desc;
  String? name;
  // // String? waitTIme;
  // num? score;
  num? price;
  num? quantity;

  String? about;
  bool highLight;
  Food(
      {this.imgUrl,
      this.desc,
      this.name,
      // // this.waitTIme,
      // this. score,
      this.price,
      this.quantity,
      this.about,
      this.highLight = false});
  static List<Food> generateRecommendFoods() {
    return [
      Food(
        imgUrl: 'assets/GC_menu/ALOOGOBIMUTTER.png',
        desc: 'veg',
        name: 'ALOO GOBI MUTTER',
        // waitTIme: '5min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about:
            'This aloo gobi matar is a dry version of a side dish made with potatoes, cauliflower and green peas cooked in spices like cumin and the usual suspects.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BAKEDCORNSPINACH.png',
        desc: 'veg',
        name: 'BAKED CORN SPINACH',
        // waitTIme: '10min',
        // score: 4.8,
        price: 235,
        quantity: 1,
        about:
            'Corn and Spinach baked pasta - this dish is the outcome of Venkatesh Bhat Samayal Samayal recipes. He had made a baked corn and spinach dish.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BAKEDVEG.png',
        desc: 'veg',
        name: 'BAKED VEG',
        // waitTIme: '25min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about:
            'This is hands down the best way to eat vegetables. When roast them it adds depth and delicious flavor, and they finish with the perfect texture',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BARKACHUMBER.png',
        desc: 'veg',
        name: 'BAR KACHUMBER',
        // waitTIme: '10min',
        // score: 4.3,
        price: 50,
        quantity: 1,
        about:
            'Kachumber resembles several staple salad dishes from cuisines, like kachumbari in the Great Lakes region of Africa or the famous Israeli salad.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHILLYPANEER.png',
        desc: 'veg',
        name: 'CHILLY PANEER',
        // waitTIme: '12min',
        // score: 4.8,
        price: 140,
        quantity: 1,
        about:
            'Chilli Paneer is one of the popular recipe from the Indian Chinese cuisine',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/thCORN SALT PEPPER_prev_ui.png',
        desc: 'veg',
        name: 'CORN SALT PEPPER',
        // waitTIme: '15min',
        // score: 4.8,
        price: 110,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CREAMOFMASHROOMVEG.png',
        desc: 'veg',
        name: 'CREAM OF MASHROOM\nVEG',
        // waitTIme: '15min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'Made with savory herbs, cremini mushrooms and white wine in a silky coconut milk base',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CREAMOFMASHROOMVEG.png',
        desc: 'veg',
        name: 'CREAM OF SPINACH VEG',
        // waitTIme: '15min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about: 'Loaded with flavor, easy to make, and totally free from dairy',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CREAMOFTOMATOVEG.png',
        desc: 'veg',
        name: 'CREAM OF TOMATO VEG',
        // waitTIme: '15min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            ' rich tomato soup that’s perfect for enjoying as a hearty lunch or light dinner',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CRIPSYHONEYPANEER.png',
        desc: 'veg',
        name: 'CRIPSY HONEY PANEER',
        // waitTIme: '20min',
        // score: 4.8,
        price: 170,
        quantity: 1,
        about:
            'Crispy Honey Chilli Paneer is one of the popular recipe from the Indian Chinese cuisine',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CRISPYHONEYPOTATO.png',
        desc: 'veg',
        name: 'CRISPY HONEY POTATO',
        // waitTIme: '20min',
        // score: 4.8,
        price: 140,
        quantity: 1,
        about:
            'The combination of warm potatoes with crispy buttery skin tossed through with creamy Honey Mustard Dressing is a stellar combination in this tasty Honey Mustard Warm Potato Salad.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DALFRY.png',
        desc: 'veg',
        name: 'DAL FRY',
        // waitTIme: '10min',
        // score: 4.8,
        price: 75,
        quantity: 1,
        about:
            'Dal fry is a delicious Indian dish made with lentils, spices and herbs.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DALMAKHANI.png',
        desc: 'veg',
        name: 'DAL MAKHANI',
        // waitTIme: '10min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about:
            'Creamy & buttery Dal Makhani is one of India"s most special and popular dal. Black lentils are cooked with lot of butter and cream making it a special dish. Best enjoyed with naan!',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DAL TADKA_prev_ui.png',
        desc: 'veg',
        name: 'DAL TADKA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about:
            'Smokey and restaurant style Dal Tadka tempered with ghee and spices! This dal is super comforting and makes a great meal with boiled rice.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DHABA DAL_prev_ui.png',
        desc: 'veg',
        name: 'DHABA DAL',
        // waitTIme: '10min',
        // score: 4.8,
        price: 95,
        quantity: 1,
        about:
            'This dal is inspired from the dals served at Punjabi dhabas. made the dal more healthy by using 5 lentils.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DUMPLING POTATO_prev_ui.png',
        desc: 'veg',
        name: 'DUMPLING POTATO',
        // waitTIme: '10min',
        // score: 4,
        price: 175,
        quantity: 1,
        about:
            'Potato Dumplings are a frequent side for roasts or other meat dishes in Germany.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GARLIC PANEER_prev_ui.png',
        desc: 'veg',
        name: 'GARLIC PANEER',
        // waitTIme: '10min',
        // score: 4.8,
        price: 140,
        quantity: 1,
        about:
            'paneer is a popular North Indian dish made with paneer (Indian cottage cheese ), khoya (thickened milk), onion, garlic, ginger, tomato and Indian spices. It is a gravy dish and is usually spicy in taste. ',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GARLIC PANEER TIKKA_prev_ui.png',
        desc: 'veg',
        name: 'GARLIC PANEER TIKKA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'paneer is a popular North Indian dish made with paneer (Indian cottage cheese ), khoya (thickened milk), onion, garlic, ginger, tomato and Indian spices. It is a gravy dish and is usually spicy in taste.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GRILLED PANEER_prev_ui.png',
        desc: 'veg',
        name: 'GRILLED PANEER',
        // waitTIme: '15min',
        // score: 4.8,
        price: 275,
        quantity: 1,
        about:
            'Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/JEERA ALOO_prev_ui.png',
        desc: 'veg',
        name: 'JEERA ALOO',
        // waitTIme: '10min',
        // score: 4.8,
        price: 75,
        quantity: 1,
        about: 'Indian Dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/KADHI_prev_ui.png',
        desc: 'veg',
        name: 'KADHI',
        // waitTIme: '5min',
        // score: 4.8,
        price: 50,
        quantity: 1,
        about: 'A indian dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/KHATTE KARARE ALOO_prev_ui.png',
        desc: 'veg',
        name: 'KHATTE KARARE ALOO',
        // waitTIme: '5min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about:
            'Khatte aloo is a traditional Indian vegetable dish originating from North India. ratatouille is, by its very definition, a combination of vegetables fried and then simmered in a tomato sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/LACCHHA PANEER_prev_ui.png',
        desc: 'veg',
        name: 'LACCHHA PANEER',
        // waitTIme: '10min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about:
            'Paneer , also known as ponir (pronounced ) or Indian cottage cheese, is a fresh acid-set cheese common in the Indian subcontinent (Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan and Sri Lanka) made from cow or buffalo milk.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/LASOONI PALAK_prev_ui.png',
        desc: 'veg',
        name: 'LASOONI PALAK',
        // waitTIme: '15min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about: ' Lasooni Palak, or Saag as its called in some places',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MASALA KHICHDI_prev_ui.png',
        desc: 'veg',
        name: 'MASALA KHICHDI',
        // waitTIme: '10min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about:
            'Khichdi is a popular traditional staple in Haryana, specially in the rural areas.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MIX VEG_prev_ui.png',
        desc: 'veg',
        name: 'MIX VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about: 'pure vegan dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MIX VEG RAITA_prev_ui.png',
        desc: 'veg',
        name: 'MIX VEG RAITA',
        // waitTIme: '5min',
        // score: 4.8,
        price: 50,
        quantity: 1,
        about: 'mix vegetable raita',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PALAK PANEER_prev_ui.png',
        desc: 'veg',
        name: 'PALAK PANEER',
        // waitTIme: '15min',
        // score: 4.8,
        price: 160,
        quantity: 1,
        about: 'veg dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER BUTTER MASALA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER BUTTER MASALA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about: 'veg dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER DO PYAZA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER DO PYAZA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 160,
        quantity: 1,
        about:
            'Paneer do pyaza recipe - Do pyaza or dopiaza is a dish named after Akbar Mullah Do Piaza who created the dish during the mughal era. Though the original version was made with meat, the vegetarian versions like paneer do pyaza and mushroom do pyaza are also popular in Indian restaurants.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER KASTURI TIKKA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER KASTURI TIKKA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 225,
        quantity: 1,
        about:
            'Paneer tikka. Paneer tikka, as served in a restaurant in Goa, India. Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER KULCHA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER KULCHA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'Amritsari kulcha or amritsari naan, is a modern recipe which has become one of the favorite breakfast choices for the local population of Amritsar.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER MALAI HARIMIRCH_prev_ui.png',
        desc: 'veg',
        name: 'PANEER MALAI\nHARIMIRCH',
        // waitTIme: '10min',
        // score: 4.8,
        price: 225,
        quantity: 1,
        about: 'Paneer malai harimirch it is veg dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER PASTUNI_prev_ui.png',
        desc: 'veg',
        name: 'PANEER PASTUNI',
        // waitTIme: '10min',
        // score: 4.8,
        price: 225,
        quantity: 1,
        about: 'veg dish.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER PEPPER SALT_prev_ui.png',
        desc: 'veg',
        name: 'PANEER PEPPER SALT',
        // waitTIme: '20min',
        // score: 4.8,
        price: 140,
        quantity: 1,
        about: 'A veg dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER SALSA TIKKA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER SALSA TIKKA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 225,
        quantity: 1,
        about:
            'Paneer tikka. Paneer tikka, as served in a restaurant in Goa, India. Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER SEEKH KABAB_prev_ui.png',
        desc: 'veg',
        name: 'PANEER SEEKH KABAB',
        // waitTIme: '10min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about:
            'The seekh kebab (Pashto: سیخ کباب, Urdu: سیخ کباب, Hindi: सीख कबाब) is a type of kebab, popular in South Asia, originating in India and Pakistan.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER TIKKA_prev_ui.png',
        desc: 'veg',
        name: 'PANEER TIKKA',
        // waitTIme: '20min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Paneer tikka. Paneer tikka, as served in a restaurant in Goa, India. Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER TIKKA MASALA _prev_ui.png',
        desc: 'veg',
        name: 'PANEER TIKKA MASALA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 180,
        quantity: 1,
        about:
            'Paneer tikka. Paneer tikka, as served in a restaurant in Goa, India. Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER TIKKA ROLL_prev_ui.png',
        desc: 'Veg-Roll',
        name: 'PANEER TIKKA ROLL',
        // waitTIme: '20min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about: 'paneer veg roll',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER TIKKA SHASLIK_prev_ui.png',
        desc: 'veg',
        name: 'PANEER TIKKA SHASLIK',
        // waitTIme: '30min',
        // score: 4.8,
        price: 240,
        quantity: 1,
        about:
            'The extremely tasty paneer shashlik tikka marries the aroma so well that the flavors burst instantly at the very first bite! It is a healthy meal made of paneer',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PASTA ALFREDO_prev_ui.png',
        desc: 'pasta',
        name: 'PASTA ALFREDO',
        // waitTIme: '10min',
        // score: 4.8,
        price: 180,
        quantity: 1,
        about:
            'Alfredo Pasta, the traditional recipe, made with only 3 ingredients, fettuccine, parmesan cheese and butter.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PASTA ALFREDO VEG_prev_ui.png',
        desc: 'pasta',
        name: 'PASTA ALFREDO VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about:
            ' Alfredo Pasta, the traditional recipe, made with only 3 ingredients, fettuccine, parmesan cheese and butter.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PASTA ARABIATA_prev_ui.png',
        desc: 'pasta',
        name: 'PASTA ARABIATA',
        // waitTIme: '20min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'Arrabiata is a spicy sauce made with garlic, tomatoes, and red chili peppers cooked in olive oil.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PASTA ARABIATA VEG_prev_ui.png',
        desc: 'pasta',
        name: 'PASTA ARABIATA VEG',
        // waitTIme: '20min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'Arrabiata is a spicy sauce made with garlic, tomatoes, and red chili peppers cooked in olive oil',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/STIR FRY VEG_prev_ui.png',
        desc: 'veg',
        name: 'STIR FRY VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about: 'This gorgeous, luscious stir-fry will knock your socks off!',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/STUFFED KULCHA_prev_ui.png',
        desc: 'veg',
        name: 'STUFFED KULCHA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 40,
        quantity: 1,
        about:
            'Amritsari Kulcha is crisp as well as soft leavened bread which is stuffed with boiled and mashed potatoes and spices. This bread is similar to Naan.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/STUFFED_MUSHROOMS_prev_ui.png',
        desc: 'veg',
        name: 'STUFFED MUSHROOM',
        // waitTIme: '20min',
        // score: 4.8,
        price: 175,
        quantity: 1,
        about:
            'These delicious bite-sized Stuffed Mushrooms are the perfect appetizer for any party!',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/SWEET CORN SOUP VEG_prev_ui.png',
        desc: 'Soup',
        name: 'SWEET CORN SOUP VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about: 'veg soup',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TAI PAI PANEER_prev_ui.png',
        desc: 'veg',
        name: 'TAI PAI PANEER',
        // waitTIme: '30min',
        // score: 4.8,
        price: 235,
        quantity: 1,
        about:
            'his is our usual Paneer Chilly with a twist. Taipei Paneer Chilly is a sweet and spicy version.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TANDOORI KALIMIRCH ALOO_prev_ui.png',
        desc: 'veg',
        name: 'TANDOORI KALIMIRCH \n ALOO',
        // waitTIme: '10min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about: 'veg dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TANDOORI KALIMIRCH PANEER_prev_ui.png',
        desc: 'veg',
        name: 'TANDOORI KALIMIRCH\nPANEER',
        // waitTIme: '30min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about: 'Paneer Tikka Kali Mirch.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TANDOORI MUSHROOM_prev_ui.png',
        desc: 'veg',
        name: 'TANDOORI MUSHROOM',
        // waitTIme: '20min',
        // score: 4.8,
        price: 150,
        quantity: 1,
        about:
            ' just need to marinate the mushrooms and then grill or bake the mushrooms in the oven.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TANDOORI PANEER STIR FRY_prev_ui.png',
        desc: 'veg',
        name: 'TANDOORI PANEER STIR\n FRY',
        // waitTIme: '20min',
        // score: 4.8,
        price: 220,
        quantity: 1,
        about:
            'Indian Paneer Stir Fry is comfort food that involves fried cheese but maintains a healthy dose of veggies! Its gluten free and vegetarian.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TRIANGLE VEG_prev_ui.png',
        desc: 'veg',
        name: 'TRIANGLE VEG',
        // waitTIme: '15min',
        // score: 4.8,
        price: 240,
        quantity: 1,
        about: 'indian dish known as Samosa',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG BIRYANI_prev_ui.png',
        desc: 'veg',
        name: 'VEG BIRYANI',
        // waitTIme: '30min',
        // score: 4.8,
        price: 140,
        quantity: 1,
        about: 'veg biryani',
        highLight: true,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG GRILLED SANDWICH_prev_ui.png',
        desc: 'Sandwich',
        name: 'VEG GRILLED SANDWICH',
        // waitTIme: '20min',
        // score: 4.8,
        price: 75,
        quantity: 1,
        about:
            'sandwich is a type of vegetarian sandwich consisting of a vegetable filling between bread. ',
        highLight: false,
      ),
      // Food(
      //   imgUrl: 'assets/GC_menu/VEG KEEMA KASTURI.png',
      //   desc: 'veg',
      //   name: 'VEG KEEMA KASTURI',
      // //   waitTIme: '10min',
      //   // score: 4.8,
      //   price: 134,
      //   quantity: 1,
      //   about:
      //       'veg kheema recipe: indian recipe with minced veggies. kheema is a hindi word which means to mince. this is a nice & delicious way to include veggies in diet',
      //   highLight: false,
      // ),
      Food(
        imgUrl: 'assets/GC_menu/VEG KOFTA_prev_ui.png',
        desc: 'veg',
        name: 'VEG KOFTA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 130,
        quantity: 1,
        about:
            'Vegetable Kofta Curry is an exotic Indian gravy dish that comprises of two parts Kofta and the curry.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG NOODLES_prev_ui.png',
        desc: 'Noodles',
        name: 'VEG NOODLES',
        // waitTIme: '20min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about:
            'Char kway teow – Chinese–inspired dish commonly served in Malaysia and Singapore.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG ROLL_prev_ui.png',
        desc: 'Roll',
        name: 'VEG ROLL',
        // waitTIme: '10min',
        // score: 4.8,
        price: 100,
        quantity: 1,
        about: 'Indian Dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG SANDWICH_prev_ui.png',
        desc: 'Sandwich',
        name: 'VEG SANDWICH',
        // waitTIme: '20min',
        // score: 4.8,
        price: 65,
        quantity: 1,
        about:
            'Vegetable sandwich is a type of vegetarian sandwich consisting of a vegetable filling between bread.',
        highLight: false,
      ),
      // Food(
      //   imgUrl:
      //       'assets/GC_menu/VEG SCHEZWAN FINGER HONEY SAUCE_prev_ui.png.png',
      //   desc: 'Sauce',
      //   name: 'VEG SCHEZWAN FINGER\nHONEY SAUCE',
      // //   waitTIme: '5min',
      //   // score: 4.8,
      //   price: 160,
      //   quantity: 1,
      //   about: ' sauce',
      //   highLight: false,
      // ),
      Food(
        imgUrl: 'assets/GC_menu/VEG SPRING ROLL_prev_ui.png',
        desc: 'Roll',
        name: 'VEG SPRING ROLL',
        // waitTIme: '10min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about:
            'Spring roll is a fried dish usually available as a dim sum. They typically contain minced pork, shredded carrot, bean sprouts and other vegetables served with dipping sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG STEAK SIZZLER_prev_ui.png',
        desc: 'Roti/Naan',
        name: 'VEG STEAK SIZZLER',
        // waitTIme: '30min',
        // score: 4.8,
        price: 300,
        quantity: 1,
        about:
            'The dish has been described as ... fish or vegetable patty, served on an oval shaped metal or stone hot plate, kept on a wooden base. The word "sizzler" comes from the sizzle that one hears after heating the dish under a grill.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG STROGENOFF _prev_ui.png',
        desc: 'veg',
        name: 'VEG STROGENOFF',
        // waitTIme: '20min',
        // score: 4.8,
        price: 300,
        quantity: 1,
        about:
            'In Brazilian Portuguese it is called Strogonoff or Estrogonofe . Stroganoff is also popular in Nordic countries',
        highLight: false,
      ),
      // Food(
      //   imgUrl: 'assets/GC_menu/WAFFERS.png',
      //   desc: 'veg',
      //   name: 'WAFFERS',
      // //   waitTIme: '20min',
      //   // score: 4.8,
      //   price: 25,
      //   quantity: 1,
      //   about: 'swaffers.',
      //   highLight: false,
      // ),
    ];
  }

  static List<Food>? generatePopularFood() {
    return [
      Food(
          imgUrl: 'assets/GC_menu/BHEJAMASALA.png',
          desc: 'Non-veg',
          name: 'BHEJA MASALA',
          // waitTIme: '20min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about:
              ' Bheja Fry is popular dish which actually uses brains of goat, sheep or lamb cooked in a spicy masala. The dish is quite popular in Hyderabad and Mumbai, the dish is quite literally mind blowing',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BHUNACHICKEN.png',
          desc: 'Most Popular',
          name: 'BHUNA CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'This easy, healthy chicken curry is great for a weekend treat and is a guaranteed crowd-pleaser. No one could refuse a plate of this indulgent chicken bhuna',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BHUNAMUTTON.png',
          desc: 'Most Popular',
          name: 'BHUNA MUTTON',
          // waitTIme: '20min',
          // score: 4.8,
          price: 240,
          quantity: 1,
          about:
              ' A popular Indian recipe, Mutton Bhuna Gosht is a mouth-watering delicacy that is popular across India and Pakistan',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BLACKPEPPERCHICKEN.png',
          desc: 'Most Popular',
          name: 'BLACK PEPPER CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'Black Pepper Chicken is prepared with marinated diced chicken, celery, onions & fresh ground black pepper, tossed in a wok with a mild ginger soy sauce.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BLACKPEPPERFISH.png',
          desc: 'Most Popular',
          name: 'BLACK PEPPER FISH',
          // waitTIme: '25min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about: 'black paper fish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BOILEDEGG.png',
          desc: 'Most Popular',
          name: 'BOILED EGG',
          // waitTIme: '10min',
          // score: 4.8,
          price: 35,
          quantity: 1,
          about:
              'Boiled eggs are eggs, typically from a chicken, cooked with their shells unbroken, usually by immersion in boiling water. Hard-boiled eggs are cooked so that the egg white and egg yolk both solidify, while soft-boiled eggs may leave the yolk, and sometimes the white, at least partially liquid ',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BUTTERCHICKENFULL.png',
          desc: 'Most Popular',
          name: 'BUTTER CHICKEN FULL',
          // waitTIme: '30min',
          // score: 4.8,
          price: 590,
          quantity: 1,
          about:
              'Butter chicken, traditionally known as Murgh makhani, (pronounced [mʊrg ˈmək.kʰə.ni]) is a type of curry made from chicken with a spiced tomato and butter (makhan) sauce. Its sauce is known for its rich texture. In addition sometimes the cream gives the curry sauce a silky smooth rich texture',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BUTTERCHICKENHALF.png',
          desc: 'Most Popular',
          name: 'BUTTER CHICKEN HALF',
          // waitTIme: '30min',
          // score: 4.8,
          price: 310,
          quantity: 1,
          about:
              'Butter chicken, traditionally known as Murgh makhani, (pronounced [mʊrg ˈmək.kʰə.ni]) is a type of curry made from chicken with a spiced tomato and butter (makhan) sauce. Its sauce is known for its rich texture. In addition sometimes the cream gives the curry sauce a silky smooth rich texture',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/BUTTERCHICKENPLATE.png',
          desc: 'Most Popular',
          name: 'BUTTER CHICKEN PLATE',
          // waitTIme: '30min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about:
              'Butter chicken, traditionally known as Murgh makhani, (pronounced [mʊrg ˈmək.kʰə.ni]) is a type of curry made from chicken with a spiced tomato and butter (makhan) sauce. Its sauce is known for its rich texture. In addition sometimes the cream gives the curry sauce a silky smooth rich texture',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHEESEOMLETTERSANDWICH.png',
          desc: 'Sandwich',
          name: 'CHEESE OMLET\nSANDWICH',
          // waitTIme: '50min',
          // score: 4.8,
          price: 90,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHEESESEEKHKABAB.png',
          desc: 'non-veg',
          name: 'CHEESE SEEKH KABAB',
          // waitTIme: '50min',
          // score: 4.8,
          price: 185,
          quantity: 1,
          about: 'seekh kebabs popular in India',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENBIRYANI.png',
          desc: 'Most Popular',
          name: 'CHICKEN BIRYANI',
          // waitTIme: '30min',
          // score: 4.8,
          price: 170,
          quantity: 1,
          about:
              'Biryani is a mixed rice dish originating among the Muslims of the Indian subcontinent. It is made with Indian spices, rice, either with meat (chicken, beef, goat, lamb, prawn, fish), or eggs or vegetables such as potatoes. Biryani is one of the most popular dishes in South',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENDOPYAZA.png',
          desc: 'non-veg',
          name: 'CHICKEN DO PYAZA',
          // waitTIme: '25min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'Chicken do pyaza literally means chicken with double onions! This ultimate chicken do pyaza curry with double the onion makes my day doubly happier!',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKNGARLICTIKKA.png',
          desc: 'non-veg',
          name: 'CHICKEN GARLIC TIKKA',
          // waitTIme: '25min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'Tomato Chicken Curry (Tamatar Murgh) is an Indian chicken curry cooked with lots of fresh tomatoes and mild spices. It goes very well with Indian bread or steamed rice.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENGRILLEDSANDWICH.png',
          desc: 'Sandwich',
          name: 'CHICKEN GRILLED \n SANDWICH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 85,
          quantity: 1,
          about:
              'Tomato Chicken Curry (Tamatar Murgh) is an Indian chicken curry cooked with lots of fresh tomatoes and mild spices. It goes very well with Indian bread or steamed rice.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENLOLLYPOP.png',
          desc: 'non-veg',
          name: 'CHICKEN LOLLY POP',
          // waitTIme: '30min',
          // score: 4.8,
          price: 240,
          quantity: 1,
          about:
              'Chicken lollipop is an  popular in Indo-Chinese cuisine.Chicken lollipop is, essentially a frenched chicken winglet, wherein the meat is cut loose from the bone end and pushed down creating a lollipop appearance. It is usually served hot with Szechuan sauce.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENMALAIHARIMIRCH.png',
          desc: 'non-veg',
          name: 'CHICKEN MALAI\n HARIMIRCH',
          // waitTIme: '30min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: 'it is an non-veg dish ',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENMALAITIKKA.png',
          desc: 'Most Popular',
          name: 'CHICKEN MALAI TIKKA',
          // waitTIme: '25min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'Malai tikka refers to grilled supreme of chicken with ginger, garlic, green chilli, cream-cheese, coriander-stem and cardamom.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENMASALA.png',
          desc: 'non-veg',
          name: 'CHICKEN MASALA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: 'non-veg dish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENNOODLES.png',
          desc: 'noodles',
          name: 'CHICKEN NOODLES',
          // waitTIme: '30min',
          // score: 4.8,
          price: 130,
          quantity: 1,
          about:
              'Quick Creamy Chicken & Noodles is one of those recipes that you turn to when dinnertime is looming',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENPAHADITIKKA.png',
          desc: 'non-veg',
          name: 'CHICKEN PAHADI TIKKA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENPASTUNITIKKA.png',
          desc: 'non-veg',
          name: 'CHICKEN PASTUNI TIKKA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 250,
          quantity: 1,
          about: 'non-veg dish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENPEPPERSALT.png',
          desc: 'non-veg',
          name: 'CHICKEN PEPPER SALT',
          // waitTIme: '30min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENPESHAWARI.png',
          desc: 'non-veg',
          name: 'CHICKEN PESHAWARI',
          // waitTIme: '40min',
          // score: 4.8,
          price: 275,
          quantity: 1,
          about:
              'This is an aromatic chicken recipe with the addition of dry roasted ground spices and popular both in North Indian and Pakistani cuisine.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENROGANJOSH.png',
          desc: 'Most Popular',
          name: 'CHICKEN ROGAN JOSH',
          // waitTIme: '30min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'Rogan Josh is one of the heavy ... Butter Chicken, Tikka Masala and Tandoori.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSALSTIKKA.png',
          desc: 'non-veg',
          name: 'CHICKEN SALSA TIKKA',
          // waitTIme: '20min',
          // score: 4.8,
          price: 250,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSANDWICH.png',
          desc: 'sandwich',
          name: 'CHICKEN SANDWICH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 75,
          quantity: 1,
          about: 'Chicken sandwiches are so clucking good',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSEEKHKABAB.png',
          desc: 'non-veg',
          name: 'CHICKEN SEEKH KABAB',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              'The seekh kebab (Pashto: سیخ کباب, Urdu: سیخ کباب, Hindi: सीख कबाब) is a type of kebab, popular in South Asia, originating in India and Pakistan. It is made with spiced, minced or ground meat, usually lamb, beef, or chicken, formed into cylinders on skewers and grilled. ',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSPRINGROLL.png',
          desc: 'non-veg',
          name: 'CHICKEN SPRING ROLL',
          // waitTIme: '20min',
          // score: 4.8,
          price: 160,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSTEAKSIZZLER.png',
          desc: 'Most Popular',
          name: 'CHICKEN STEAK SIZZLER',
          // waitTIme: '30min',
          // score: 4.8,
          price: 325,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENSTROGENOFF.png',
          desc: 'Most Popular',
          name: 'CHICKEN STROGENOFF',
          // waitTIme: '40min',
          // score: 4.8,
          price: 325,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENTIKKA.png',
          desc: 'Most Popular',
          name: 'CHICKEN TIKKA',
          // waitTIme: '20min',
          // score: 4.8,
          price: 150,
          quantity: 1,
          about:
              'Chicken tikka is a chicken dish originating in the Indian subcontinent during the Mughal era, the dish is popular in India, Bangladesh and Pakistan. It is traditionally small pieces of boneless chicken baked using skewers on a brazier called angeethi or over charcoal after marinating',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENTIKKAMASALA.png',
          desc: 'non-veg',
          name: 'CHICKEN TIKKA MASALA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about:
              'Chicken tikka is a chicken dish originating in the Indian subcontinent during the Mughal era, the dish is popular in India, Bangladesh and Pakistan. It is traditionally small pieces of boneless chicken baked using skewers on a brazier called angeethi or over charcoal after marinating',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENTIKKAROLL.png',
          desc: 'Most Popular',
          name: 'CHICKEN TIKKA ROLL',
          // waitTIme: '30min',
          // score: 4.8,
          price: 190,
          quantity: 1,
          about:
              'Chicken tikka is a chicken dish originating in the Indian subcontinent during the Mughal era, the dish is popular in India, Bangladesh and Pakistan. It is traditionally small pieces of boneless chicken baked using skewers on a brazier called angeethi or over charcoal after marinating',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENTRIPPLES_ZFRIEDRICE.png',
          desc: 'non-veg',
          name: 'CHICKEN TRIPPLE S/Z\n FRIED RICE',
          // waitTIme: '20min',
          // score: 4.8,
          price: 250,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHILLYCHICKEN.png',
          desc: 'non-veg',
          name: 'CHILLY CHICKEN',
          // waitTIme: '30min',
          // score: 4.8,
          price: 160,
          quantity: 1,
          about:
              'Chilli chicken is a popular Indo-Chinese dish of chicken of Hakka Chinese heritage. In India, this may include a variety of dry chicken preparations.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CHILLYFISH.png',
          desc: 'non-veg',
          name: 'CHILLY FISH',
          // waitTIme: '30min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CLEARSOUPNONVEG.png',
          desc: 'non-veg soup',
          name: 'CLEAR SOUP NON VEG',
          // waitTIme: '30min',
          // score: 4.8,
          price: 100,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/CRISPYHONEYCHICKEN.png',
          desc: 'non-veg',
          name: 'CRISPY HONEY CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 190,
          quantity: 1,
          about:
              'Crispy Honey Chicken with the crispiest coating ever and a sweet honey glaze',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/EGG BIRYANI_prev_ui.png',
          desc: 'non-veg',
          name: 'EGG BIRYANI',
          // waitTIme: '20min',
          // score: 4.8,
          price: 140,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/EGG CURRY_prev_ui.png',
          desc: 'non-veg',
          name: 'EGG CURRY',
          // waitTIme: '50min',
          // score: 4.8,
          price: 90,
          quantity: 1,
          about:
              ' EGG Curry  is an Indian dish EGG curry It goes very well with Indian bread or steamed rice.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/EGG FRIED RICE_prev_ui.png',
          desc: 'non-veg',
          name: 'EGG FRIED RICE',
          // waitTIme: '20min',
          // score: 4.8,
          price: 125,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/EGG NOODLES_prev_ui.png',
          desc: 'noodles',
          name: 'EGG NOODLES',
          // waitTIme: '50min',
          // score: 4.8,
          price: 125,
          quantity: 1,
          about:
              'Noodles are a type of food made from unleavened dough which is rolled flat and cut, stretched or extruded, into long strips or strings. Noodles can be refrigerated for short-term storage or dried and stored for future use',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/EGG PAKODA_prev_ui.png',
          desc: 'non-veg',
          name: 'EGG PAKODA',
          // waitTIme: '10min',
          // score: 4.8,
          price: 110,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH AMRITSARI_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH AMRITSARI',
          // waitTIme: '10min',
          // score: 4.8,
          price: 220,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH CURRY_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH CURRY',
          // waitTIme: '25min',
          // score: 4.8,
          price: 210,
          quantity: 1,
          about:
              'Fish head curry, a Singaporean dish where the head of an Ikan Merah (red snapper, literally "Red fish") is used · Machher Jhol (also called "Machher Ghonta") a traditional Bengali and Oriya fish curry',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH FINGER_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH FINGER',
          // waitTIme: '10min',
          // score: 4.8,
          price: 220,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH FRY BENGALI STYLE _prev_ui.png',
          desc: 'non-veg',
          name: 'FISH FRY BENGALI\nSTYLE',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about:
              ' Bengali Fish Fry is a popular snack from streets of Kolkata. We have unadulterated love for our Kolkata style Fish Fry, a popular snack from streets of Kolkata.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH TIKKA_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH GARLIC TIKKA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH KALIWADA_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH KALIWADA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about: 'non-veg dish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH MALAI HARIMIRCH_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH MALAI HARIMIRCH',
          // waitTIme: '30min',
          // score: 4.8,
          price: 240,
          quantity: 1,
          about: 'non veg dish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH MALAI TIKKA_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH MALAI TIKKA',
          // waitTIme: '40min',
          // score: 4.8,
          price: 240,
          quantity: 1,
          about:
              'Fish Tikka (absolutely delicious recipe of Barbecue Fish Tikka ingredients and cooking method) About Barbecue Fish Tikka: Marinated fish slowly roasted on hot tandoor.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/FISH TIKKA_prev_ui.png',
          desc: 'non-veg',
          name: 'FISH TIKKA',
          // waitTIme: '30min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about:
              'Fish Tikka (absolutely delicious recipe of Barbecue Fish Tikka ingredients and cooking method) About Barbecue Fish Tikka: Marinated fish slowly roasted on hot tandoor.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/GARLIC CHICKEN_prev_ui.png',
          desc: 'non-veg',
          name: 'GARLIC CHICKEN',
          // waitTIme: '10min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/thGARLIC FISH_prev_ui.png',
          desc: 'non-veg',
          name: 'GARLIC FISH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/GHARGUTI CHICKEN_prev_ui.png',
          desc: 'non-veg',
          name: 'GHARGUTI CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/GRILLED CHICKEN_prev_ui.png',
          desc: 'non-veg',
          name: 'GRILLED CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 300,
          quantity: 1,
          about: '.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/HOT & SOUR SOUP NON VEG_prev_ui.png',
          desc: 'non-veg',
          name: 'HOT & SOUR SOUP\n NON VEG',
          // waitTIme: '10min',
          // score: 4.8,
          price: 100,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/KADAI CHICKEN_prev_ui.png',
          desc: 'non-veg',
          name: 'KADAI CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 180,
          quantity: 1,
          about: 'non-veg dish',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/KEEMA KALEJI_prev_ui.png',
          desc: 'non-veg',
          name: 'KEEMA KALEJI',
          // waitTIme: '50min',
          // score: 4.8,
          price: 260,
          quantity: 1,
          about:
              'dish from the Indian subcontinent associated with the Mughals. The term is derived from Chaghatai Turkic قیمه (minced meat) which is cognate with Turkish kıyma.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/LACCHHA CHICKEN_prev_ui.png',
          desc: 'non-veg',
          name: 'LACCHHA CHICKEN',
          // waitTIme: '20min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/LEMON BUTTER FISH_prev_ui.png',
          desc: 'non-veg',
          name: 'LEMON BUTTER FISH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about: 'lemon butter fish cooked in a simple lemon butter sauce',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MANCHOW SOUP NON VEG_prev_ui.png',
          desc: 'non-veg',
          name: 'MANCHOW SOUP \n NON VEG',
          // waitTIme: '10min',
          // score: 4.8,
          price: 200,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MIXED FRIED RICE (PRAWNS)_prev_ui.png',
          desc: 'non-veg',
          name: 'MIXED FRIED RICE\n(PRAWNS)',
          // waitTIme: '20min',
          // score: 4.8,
          price: 450,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MIXED NOODLES(PRAWNS).png',
          desc: 'non-veg',
          name: 'MIXED NOODLES(PRAWNS)',
          // waitTIme: '50min',
          // score: 4.8,
          price: 480,
          quantity: 1,
          about:
              'Noodles are a type of food made from unleavened dough which is rolled flat and cut, stretched or extruded, into long strips or strings. Noodles can be refrigerated for short-term storage or dried and stored for future use. Noodles are usually cooked in boiling water.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MUSTERED FISH_prev_ui.png',
          desc: 'non-veg',
          name: 'MUSTERED FISH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 250,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MUTTON BIRYANI_prev_ui.png',
          desc: 'popular',
          name: 'MUTTON BIRYANI',
          // waitTIme: '30min',
          // score: 4.8,
          price: 210,
          quantity: 1,
          about:
              'Mutton Pulao is a dish fairly common in North Indian, South Indian and Pakistani and Turkish cuisine that incorporates mutton into a rice pilaf. The rice used is almost invariably Basmati or a close variant. Even though Mutton Pulao resembles Mutton Biryani in many respects,',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MUTTON CURRY_prev_ui.png',
          desc: 'non-veg',
          name: 'MUTTON CURRY',
          // waitTIme: '30min',
          // score: 4.8,
          price: 220,
          quantity: 1,
          about:
              'Mutton curry is a dish that is prepared from goat meat (or sometimes lamb meat) and vegetables. The dish is found in different variations across all states, countries and regions of South Asia',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/MUTTON ROGAN JOSH_prev_ui.png',
          desc: 'non-veg',
          name: 'MUTTON ROGAN JOSH',
          // waitTIme: '30min',
          // score: 4.8,
          price: 230,
          quantity: 1,
          about:
              'Rogan josh  also spelled roghan josh or roghan ghosht, is an aromatic curried meat dish of Kashmiri origin',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/OMELETTE CHEESE_prev_ui.png',
          desc: 'non-veg',
          name: 'OMELETTE CHEESE',
          // waitTIme: '20min',
          // score: 4.8,
          price: 80,
          quantity: 1,
          about: 'A cheese omelette is a great breakfast option ',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/OMELETTE MASALA_prev_ui.png',
          desc: 'non-veg',
          name: 'OMELETTE MASALA',
          // waitTIme: '50min',
          // score: 4.8,
          price: 60,
          quantity: 1,
          about:
              'Masala omelette is a popular Indian breakfast, packed with flavor.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/OMLETTE SANDWICH_prev_ui.png',
          desc: 'sandwich',
          name: 'OMLETTE SANDWICH',
          // waitTIme: '20min',
          // score: 4.8,
          price: 75,
          quantity: 1,
          about:
              'The Indian omelette sandwich is loaded with onions, chile, coriander, pepper and other spices, and the recipe is best eaten on toasted white bread.',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/SWEET CORN SOUP NON VEG_prev_ui.png',
          desc: 'non-veg',
          name: 'SWEET CORN SOUP\n NON VEG',
          // waitTIme: '10min',
          // score: 4.8,
          price: 100,
          quantity: 1,
          about: '',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/TANDOORI POMPHLET_prev_ui.png',
          desc: 'non-veg',
          name: 'TANDOORI POMPHLET',
          // waitTIme: '50min',
          // score: 4.8,
          price: 310,
          quantity: 1,
          about:
              'Fish marinated with yogurt and an assortment of masalas. Grilled till golden and crisp.. This Tandoori Pomfret recipe is Excellent and find more Great ',
          highLight: false),
      Food(
          imgUrl: 'assets/GC_menu/TANDOORI PRAWNS_prev_ui.png',
          desc: 'non-veg',
          name: 'TANDOORI PRAWNS',
          // waitTIme: '15min',
          // score: 4.8,
          price: 450,
          quantity: 1,
          about:
              'Tandoori chicken as a dish originated in the Punjab before the independence of partition of India',
          highLight: false),
    ];
  }

  static List<Food>? generateSnackFood() {
    return [
      Food(
        imgUrl: 'assets/GC_menu/ALOOBONDA.png',
        desc: 'Snacks',
        name: 'ALOO BONDA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'Aloo bonda recipe or potato bonda is a popular South Indian snack and a street food.aloo bonda literally translates to bondas that are stuffed with potatoes. These are a South Indian version of the popular Maharashtrian snack',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BISCUITROTI.png',
        desc: 'Snacks',
        name: 'BISCUIT ROTI',
        // waitTIme: '35min',
        // score: 4.8,
        price: 25,
        quantity: 1,
        about:
            'Biscuit rotti or biscuit poori is a crispy deep-fried bread with a crunchy and spicy coconut filling. Biscuit rotti is like Konkani style kachori',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BOILEDPEANUT.png',
        desc: 'Snacks',
        name: 'BOILED PEANUT',
        // waitTIme: '5min',
        // score: 4,
        price: 50,
        quantity: 1,
        about:
            'Traditional Southern hot boiled peanuts. Raw peanuts boiled in salt water for a salty, shell-shucking-worthy snack.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/BUTTERTOAST.png',
        desc: 'Snacks',
        name: 'BUTTER TOAST',
        // waitTIme: '10min',
        // score: 4.8,
        price: 40,
        quantity: 1,
        about: 'Buttered toast is one of the easiest grab-and-go meals',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHEESEBALL.png',
        desc: 'Starter',
        name: 'CHEESE BALL',
        // waitTIme: '15min',
        // score: 4.2,
        price: 150,
        quantity: 1,
        about:
            'This Classic Cheese Ball recipe makes the perfect party appetizer.  This cheese ball is made with cheddar cheese, cream cheese, green onion and spices, and coated in chopped pecans.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHEESECHERRYPINEAPPLE.png',
        desc: 'Starter',
        name: 'CHERRY PINEAPPLE',
        // waitTIme: '5min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about:
            'Pineapple Cheese Cherry is a complimentary dish,the cherry adds sweetness while the pineapple adds the sweet and sour taste. The mixture of all these flavors in each mouthful, makes it so different and delicious.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHEESECORNTIKKI.png',
        desc: 'Starter',
        name: 'CHEESE CORN TIKKI',
        // waitTIme: '15min',
        // score: 4.8,
        price: 130,
        quantity: 1,
        about:
            ' spicy paste of sweet corn, garlic, ginger and chillies, which gives a new dimension to this famous Indian street food’s',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHEESE GARLIC TOAST.PNG',
        desc: 'Snacks',
        name: 'CHEESE GARLIC TOAST',
        // waitTIme: '15min',
        // score: 4,
        price: 120,
        quantity: 1,
        about:
            'A mixture of cheeses, butter, and garlic all slathered on thick white bread and baked until bubbly and golden brown.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHEESEKULCHA.png',
        desc: 'Starter',
        name: 'CHEESE KULCHA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about:
            'Cheese Kulcha, which is made of yogurt, beaten eggs along with wheat flour and baking powder. The main ingredients that we use is the cheese cube which forms the filling of the kulcha. The coriander leaves and chopped green chillies are an add on to the flavour of the kulchas.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CHILLYBABYCORN.png',
        desc: 'Starter',
        name: 'CHILLY BABY CORN',
        // waitTIme: '20min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Crunchy, crispy, and flavorful Chilli baby corn is a delicious vegetarian snack ',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CLEARSOUPVEG.png',
        desc: 'Veg soup',
        name: 'CLEAR SOUP VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'soup that is light, healthy and nutritious. It is also gluten-free and vegan',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/COFFEE.png',
        desc: 'Drink',
        name: 'COFFEE',
        // waitTIme: '5min',
        // score: 4.8,
        price: 25,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CRISPYCORN.png',
        desc: 'Starter',
        name: 'CRISPY CORN',
        // waitTIme: '5min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Crispy cron is a snack made by frying corn kernels and then flavoring with spice powders',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/CRISPYVEG.png',
        desc: 'Starter',
        name: 'CRISPY VEG',
        // waitTIme: '20min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DAL SNACKS_prev_ui.png',
        desc: 'Snacks',
        name: 'DAL SNACKS',
        // waitTIme: '5min',
        // score: 4.8,
        price: 135,
        quantity: 1,
        about: 'The Best Moong Dal Snacks',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/FRENCH FRIES.png',
        desc: 'Starter',
        name: 'FRENCH FRIES',
        // waitTIme: '10min',
        // score: 4.8,
        price: 65,
        quantity: 1,
        about:
            'French fries (North American English), chips (British English), finger chips (Indian English), french-fried potatoes, or simply fries, are batonnet or allumette-cut deep-fried potatoes, originating from France',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/FRIED PAPAD_prev_ui.png',
        desc: 'Starter',
        name: 'FRIED PAPAD',
        // waitTIme: '5min',
        // score: 4.8,
        price: 15,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/KHADA SALAD_prev_ui.png',
        desc: 'Starter',
        name: 'KHADA SALAD',
        // waitTIme: '5min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'A salad is a dish consisting of mixed, mostly natural ingredients with at least one raw ingredient.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/HARA BHARA KEBAB_prev_ui.png',
        desc: 'Snacks',
        name: 'HARA BHARA KEBAB',
        // waitTIme: '10min',
        // score: 4.8,
        price: 100,
        quantity: 1,
        about:
            ' Hara bhara kabab are a popular healthy and delicious appetizer cum snack made with spinach, potatoes, peas, spices and herbs. These vegan and gluten-free spinach potato patties are filled with a burst of Indian flavors and are super addictive!',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/HOT & SOUR SOUP VEG.png',
        desc: 'veg Soup',
        name: 'HOT & SOUR SOUP VEG',
        // waitTIme: '5min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about: 'A healthy soup',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MANCHAOW SOUP VEG_prev_ui.png',
        desc: 'veg Soup',
        name: 'MANCHAOW SOUP VEG',
        // waitTIme: '10min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about: 'A healthy soup',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MANCHURIAN_prev_ui.png',
        desc: 'Starter',
        name: 'MANCHURIAN',
        // waitTIme: '10min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about:
            'Manchurian is a class of Indian Chinese dishes made by roughly chopping and deep-frying ingredients',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/ROASTED PAPAD_prev_ui.png',
        desc: 'Starter',
        name: 'ROASTED PAPAD',
        // waitTIme: '5min',
        // score: 4.8,
        price: 15,
        quantity: 1,
        about:
            ' It is usually made from dried lentils; eaten fried or roasted.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MASALA PAPAD_prev_ui.png',
        desc: 'Starter',
        name: 'MASALA PAPAD',
        // waitTIme: '5min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about:
            'A ratatouille is, by its very definition, a combination of vegetables fried and then simmered in a tomato sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MASALA PEANUT_prev_ui.png',
        desc: 'snack',
        name: 'MASALA PEANUT',
        // waitTIme: '5min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'A ratatouille is, by its very definition, a combination of vegetables fried and then simmered in a tomato sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/METHI CORN TIKKI_prev_ui.png',
        desc: 'snacks',
        name: 'METHI CORN TIKKI',
        // waitTIme: '5min',
        // score: 4.8,
        price: 100,
        quantity: 1,
        about: 'Corn Methi Tikki is a delicious Indian recipe',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MIX PAKODA_prev_ui.png',
        desc: 'snacks',
        name: 'MIX PAKODA',
        // waitTIme: '5min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'Pakora is a spiced fritter originating from the Indian subcontinent, sold by street vendors and served in restaurants in South Asia and UK. It consists of items, often vegetables such as potatoes and onions, coated in seasoned gram flour batter and deep fried.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/MOONG PAKODA_prev_ui.png',
        desc: 'snacks',
        name: 'MOONG PAKODA',
        // waitTIme: '5min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'Moong dal pakoda are quick, crunchy and tasty snack made with moong dal, spices and herbs. Pakora also known as pakoda is one of the most enjoyed tea time snack in Indian subcontinent.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/ONION PAKODA_prev_ui.png',
        desc: 'Snacks',
        name: 'ONION PAKODA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about:
            'A ratatouille is, by its very definition, a combination of vegetables fried and then simmered in a tomato sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER MALAI TIKKA_prev_ui.png',
        desc: 'snack',
        name: 'PANEER MALAI TIKKA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Malai tikka is a popular and delicious variety of tikka that is served in restaurants',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER PAHADI TIKKA_prev_ui.png',
        desc: 'snack',
        name: 'PANEER PAHADI TIKKA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Paneer tikka. Paneer tikka, as served in a restaurant in Goa, India. Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PANEER PAKODA_prev_ui.png',
        desc: 'snack',
        name: 'PANEER PAKODA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 110,
        quantity: 1,
        about:
            'paneer pakora is a deep-fried Indian snack made using paneer (Indian cottage cheese, Indian spices, and chickpea flour.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/STUFFED PANEER TIKKA_prev_ui.png',
        desc: 'Snacks',
        name: 'STUFFED PANEER TIKKA',
        // waitTIme: '15min',
        // score: 4.8,
        price: 200,
        quantity: 1,
        about:
            ' Paneer Tikka. It is an easy traditional North Indian recipe and is a favourite snack of most vegetarian food lovers.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/TANDOORI VEG PLATTER_prev_ui.png',
        desc: 'Starter',
        name: 'TANDOORI VEG PLATTER',
        // waitTIme: '20min',
        // score: 4.8,
        price: 240,
        quantity: 1,
        about: 'Tandoori Vegetable Platter is a delicious Indian Dish.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG SEEKH KEBAB_prev_ui.png',
        desc: 'Snack',
        name: 'VEG SEEKH KEBAB',
        // waitTIme: '10min',
        // score: 4.8,
        price: 145,
        quantity: 1,
        about:
            'Veg Seekh Kebab is a ground/minced kebab that is skewered & cooked over a barbeque.',
        highLight: false,
      ),
    ];
  }

  static List<Food> generateDessertFood() {
    return [
      Food(
        imgUrl: 'assets/GC_menu/BOONDIRAITA.png',
        desc: 'Dessert',
        name: 'BOONDI RAITA',
        // waitTIme: '20min',
        // score: 4.8,
        price: 50,
        quantity: 1,
        about: ' Boondi raita is a North Indian raita variety made with yogur',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/DAHI.png',
        desc: 'Dessert',
        name: 'DAHI',
        // waitTIme: '5min',
        // score: 4.8,
        price: 40,
        quantity: 1,
        about:
            'Curd is a traditional yogurt or fermented milk product, originating from the Indian subcontinent, usually prepared from cows milk, and sometimes buffalo milk, or goat milk. It is popular throughout the Indian subcontinent',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GULABJAMUN_prev_ui.png',
        desc: 'No1. in sales',
        name: 'GULABJAMUN',
        // waitTIme: '5min',
        // score: 4.8,
        price: 50,
        quantity: 1,
        about:
            'milk-solid-based sweet, originating in the Indian subcontinent and a type of mithai popular in India, Pakistan, Nepal, the Maldives (where it is known as gulab ki janu), and Bangladesh, as well as Myanmar. It is the national dessert of Pakistan.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/KULFI_prev_ui.png',
        desc: 'Dessert',
        name: 'KULFI',
        // waitTIme: '5min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about:
            'is a frozen dairy dessert originating in the Indian subcontinent in the 16th century. It is often described as "traditional Indian ice cream" and is a traditional sweet of the Indian subcontinent.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/PINEAPPLE RAITA_prev_ui.png',
        desc: 'Dessert',
        name: 'PINEAPPLE RAITA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 70,
        quantity: 1,
        about:
            'Refresh yourself with this cool, salty & sweet pineapple raita.',
        highLight: false,
      ),
    ];
  }

  static List<Food>? generateExtraFood() {
    return [
      Food(
        imgUrl: 'assets/GC_menu/AJWANIROTI.png',
        desc: 'Roti',
        name: 'AJWANI ROTI',
        // waitTIme: '50min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about:
            'Ajwain paratha is a fragrant, layered flatbread variant. These flaky parathas are made with unleavened whole wheat dough and flavored with carom seeds (ajwain). They are easy to make and pairs well with many Indian sides. Ajwain is also known as carom seeds or thymol seeds or bishops weed in English and omam or owa or ajmo in some regional Indian languages.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/JEERA ROTI_prev_ui.png',
        desc: 'Roti',
        name: 'JEERA ROTI',
        // waitTIme: '5min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about:
            'Roti (also known as chapati) is a round flatbread native to the Indian subcontinent made from stoneground whole wheat flour',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/ROTI_prev_ui.png',
        desc: 'Roti',
        name: 'ROTI',
        // waitTIme: '10min',
        // score: 4.8,
        price: 15,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/ROTI BUTTER_prev_ui.png',
        desc: 'Roti',
        name: 'ROTI BUTTER',
        // waitTIme: '10min',
        // score: 4.8,
        price: 20,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/NAAN_prev_ui.png',
        desc: 'Naan',
        name: 'NAAN',
        // waitTIme: '20min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about:
            'In South Asian cuisine, naans are typically flavored with fragrant essences, such as rosewater, khus (vetiver), or with butter or ghee melted on them. Nigella seeds are commonly added to naan as cooked in Indian, Bangladeshi and Pakistani restaurants throughout the UK.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/NAAN BUTTER_prev_ui.png',
        desc: 'Naan',
        name: 'NAAN BUTTER',
        // waitTIme: '20min',
        // score: 4.8,
        price: 35,
        quantity: 1,
        about:
            'In South Asian cuisine, naans are typically flavored with fragrant essences, such as rosewater, khus (vetiver), or with butter or ghee melted on them. Nigella seeds are commonly added to naan as cooked in Indian, Bangladeshi and Pakistani restaurants throughout the UK.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GARLIC NAAN_prev_ui.png',
        desc: 'Naan',
        name: 'GARLIC NAAN',
        // waitTIme: '5min',
        // score: 4.8,
        price: 40,
        quantity: 1,
        about:
            'It is often covered in herbs and spices such as garlic to change the taste. Naan bread is made from basic bread ingredients like wheat flour, a leavening agent (either yeast, yogurt, baking powder, or all), salt, and butter or ghee. It also is made with yogurt and milk',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/LACCHA PARATHA_prev_ui.png',
        desc: 'Paratha',
        name: 'LACCHA PARATHA',
        // waitTIme: '10min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about:
            'Laccha Paratha: It is North Indian name. It is similar to Kerala Paratha or Malabar Paratha in South India.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/LACCHA PARATHA BUTTER_prev_ui.png',
        desc: 'Paratha',
        name: 'LACCHA PARATHA\n BUTTER',
        // waitTIme: '10min',
        // score: 4.8,
        price: 35,
        quantity: 1,
        about:
            'Laccha Paratha: It is North Indian name. It is similar to Kerala Paratha or Malabar Paratha in South India.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/STEAMED RICE_prev_ui.png',
        desc: 'Rice',
        name: 'STEAMED RICE',
        // waitTIme: '10min',
        // score: 4.8,
        price: 65,
        quantity: 1,
        about: 'steam rice',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/GARLIC RICE_prev_ui.png',
        desc: 'Rice',
        name: 'GARLIC RICE',
        // waitTIme: '10min',
        // score: 4.8,
        price: 100,
        quantity: 1,
        about:
            'This is a simple Philippine fried rice bursting with the flavor and aroma of garlic.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/JEERA RICE_prev_ui.png',
        desc: 'Rice',
        name: 'JEERA RICE',
        // waitTIme: '5min',
        // score: 4.8,
        price: 80,
        quantity: 1,
        about: 'Indian Dish',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG FRIED RICE_prev_ui.png',
        desc: 'Rice',
        name: 'VEG FRIED RICE',
        // waitTIme: '50min',
        // score: 4.8,
        price: 120,
        quantity: 1,
        about:
            'Fried rice is a dish of cooked rice that has been stir-fried in a wok or a frying pan and is usually mixed with other ingredients such as eggs, vegetables, seafood, or meat',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG PULAO_prev_ui.png',
        desc: 'Rice',
        name: 'VEG PULAO',
        // waitTIme: '50min',
        // score: 4.8,
        price: 90,
        quantity: 1,
        about:
            'A ratatouille is, by its very definition, a combination of vegetables fried and then simmered in a tomato sauce.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/VEG TRIPPLE FRIED RICE_prev_ui.png',
        desc: 'Rice',
        name: 'VEG TRIPPLE\n S/Z FRIED RICE',
        // waitTIme: '20min',
        // score: 4.8,
        price: 225,
        quantity: 1,
        about:
            'Popular amongst the youngsters, this Chinese delicacy is thoroughly enjoyed by the elders too.',
        highLight: false,
      ),
      Food(
          imgUrl: 'assets/GC_menu/CHICKENFRIEDRICE.png',
          desc: 'Most Popular',
          name: 'CHICKEN FRIED RICE',
          // waitTIme: '10min',
          // score: 4.8,
          price: 130,
          quantity: 1,
          about: '',
          highLight: false),
      // Food(
      //   imgUrl: 'assets/GC_menu/BISLERI.png',
      //   desc: 'Drink',
      //   name: 'BISLERI',
      // //   waitTIme: '-',
      //   // score: 4.8,
      //   price: 20,
      //   quantity: 1,
      //   about:
      //       'Bisleri International is an Indian company incorporated in 1984 by Jayantilal Chauhan.It is best known for its brand of bottled water',
      //   highLight: false,
      // ),
      Food(
        imgUrl: 'assets/GC_menu/SOFT DRINKS_prev_ui.png',
        desc: 'Drink',
        name: 'SOFT DRINKS',
        // waitTIme: '5min',
        // score: 4.8,
        price: 24,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/EXTRA BOILED VEG_prev_ui.png',
        desc: 'Veg',
        name: 'EXTRA BOILED VEG',
        // waitTIme: '5min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/EXTRACHEESE.png',
        desc: 'Cheese',
        name: 'EXTRA CHEESE',
        // waitTIme: '5min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/EXTRA CHOP ONION, TOMATO_prev_ui.png',
        desc: 'Extra',
        name: 'EXTRA CHOP\n ONION TOMATO',
        // waitTIme: '5min',
        // score: 4.8,
        price: 25,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/EXTRA GRAVY_prev_ui.png',
        desc: 'Gravy',
        name: 'EXTRA GRAVY',
        // waitTIme: '5min',
        // score: 4.8,
        price: 60,
        quantity: 1,
        about: '',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/GC_menu/EXTRA RICE_prev_ui.png',
        desc: 'Rice',
        name: 'EXTRA RICE',
        // waitTIme: '5min',
        // score: 4.8,
        price: 30,
        quantity: 1,
        about: '',
        highLight: false,
      ),
    ];
  }
}
